//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Details
    {
        public int eventId { get; set; }
        public int categoryId { get; set; }
        public string eventName { get; set; }
        public string eventDescription { get; set; }
        public string venue { get; set; }
        public System.DateTime eventDate { get; set; }
        public int organizerId { get; set; }
        public decimal ticketPrice { get; set; }
        public int availiability { get; set; }
    
        public virtual User User { get; set; }
    }
}
